import { useMemo, useState } from 'react';
import { ArrowRight, BarChart3, CalendarDays, Check, ChevronDown, CircleDollarSign, Gauge, HeartHandshake, Languages, MapPin, Menu, Radio, Route, ShieldCheck, Sparkles, Store, Users, X, Zap } from 'lucide-react';
import { calculateEconomics } from './calculator';

const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const services = [
  {n:'01',title:'White-glove ATM placement',text:'Design-forward equipment, tailored wraps, thoughtful placement and hospitality-trained service—built to belong in premium venues.'},
  {n:'02',title:'SignalOS intelligence',text:'Live fleet health, predictive cash demand, smart dispatch and transparent reporting in one beautifully simple venue portal.'},
  {n:'03',title:'Event cash concierge',text:'Temporary capacity, on-site support and surge forecasting for festivals, private events, gaming, markets and high-volume weekends.'}
];
const innovations = [
  ['Local Loop','Turn each screen and receipt into a local discovery channel—promoting nearby Native-owned and neighborhood businesses.',Store],
  ['Cash Access Sponsorships','Let brands or community partners subsidize transaction fees at selected locations or community events.',HeartHandshake],
  ['Guest Experience Signals','Privacy-minded trend reporting helps venues understand demand windows without tracking individual customers.',Users],
  ['Community Impact Ledger','Optional reporting translates network activity into local access, vendor promotion and community contribution stories.',BarChart3],
];
const faqs = [
  ['What does a venue pay?','Placement models can be structured around venue traffic and needs—including full-service placement, shared revenue, purchase or event-specific service. Every proposal is transparent.'],
  ['How quickly are machines serviced?','SignalOS is designed to flag issues before guests notice them and route the right response. Service commitments would be defined by market and venue tier.'],
  ['Can the ATM match our brand?','Yes. Curated wraps, interface themes and placement details can make the machine feel intentional—from understated black-on-black to a full branded moment.'],
  ['What makes Sovereign Cash Co. Native-owned?','Sovereign Cash Co. is owned by a Tulalip Tribes member—not simply inspired by Native identity. That ownership guides who we build relationships with, how we show up for local businesses and how we create value beyond an ATM transaction. We prioritize honest partnerships, opportunities for Tribal and local vendors, dependable cash access and technology that helps keep more economic activity circulating close to home. Native ownership is part of the company’s leadership and accountability—not a decorative marketing claim. Any formal certifications will be displayed only after they are completed.']
];

function Mark(){return <div className="mark" aria-hidden="true"><i/><i/><i/></div>}
function Reveal({children,className=''}:{children:React.ReactNode,className?:string}){return <div className={`reveal ${className}`}>{children}</div>}

export function App(){
  const [menu,setMenu]=useState(false); const [openFaq,setOpenFaq]=useState(0);
  const [inputs,setInputs]=useState({transactions:600,surcharge:3.5,venueShare:40,lift:18});
  const calc=useMemo(()=>calculateEconomics(inputs),[inputs]);
  return <main>
    <header><a className="brand" href="#top"><Mark/><span>SOVEREIGN<br/><b>CASH CO.</b></span></a><button className="menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{[['Placements','placements'],['Services','services'],['SignalOS','signalos'],['Story','story']].map(([label,id])=><a key={id} onClick={()=>setMenu(false)} href={`#${id}`}>{label}</a>)}<a className="navCta" href="#partner">See it in your space <ArrowRight size={16}/></a></nav></header>

    <section className="hero heroPhoto" id="top"><img src={`${import.meta.env.BASE_URL}images/placement-restaurant.webp`} alt="Luxury black and copper ATM placed inside an upscale restaurant"/><div className="heroShade"/><div className="heroCopy"><p className="eyebrow"><span/> Native-owned · Locally operated</p><h1>A better ATM<br/>for <em>better places.</em></h1><p className="dek">Beautifully designed cash access for restaurants, hotels, nightlife, retail and gathering places—installed, managed and monitored for you.</p><div className="heroActions"><a className="button copper" href="#placements">Picture it in your business <ArrowRight/></a><a className="textLink" href="#partner">Request a placement review <span>↓</span></a></div></div><div className="heroProof"><span>01</span><div><small>SHOWN IN</small><b>Restaurant · Entry placement</b><em>Obsidian + copper finish</em></div></div></section>

    <div className="signal"><span><Radio/> Proactive fleet monitoring</span><span><ShieldCheck/> Fully managed placement</span><span><MapPin/> Local service & support</span><span><Sparkles/> Designed for your space</span></div>

    <section className="placements light" id="placements"><div className="placementIntro"><div><p className="eyebrow dark"><span/> Imagine it here</p><h2>Made to belong<br/>in your business.</h2></div><div><p>Generic machines look like an afterthought. Ours are selected, finished and placed to feel intentional—whether your space is warm and intimate, bright and modern, or alive after dark.</p><a href="#partner">Get a complimentary placement mockup <ArrowRight/></a></div></div><div className="placementGrid"><figure className="wide"><img src={`${import.meta.env.BASE_URL}images/placement-hotel.webp`} alt="Luxury ATM in a boutique hotel lobby"/><figcaption><span>01</span><div><b>Boutique hotels</b><small>Lobby · guest amenity</small></div></figcaption></figure><figure><img src={`${import.meta.env.BASE_URL}images/placement-nightlife.webp`} alt="Luxury ATM in an upscale cocktail and live music venue"/><figcaption><span>02</span><div><b>Bars & nightlife</b><small>Entry · high-demand access</small></div></figcaption></figure><figure><img src={`${import.meta.env.BASE_URL}images/placement-retail.webp`} alt="Luxury ATM in a local retail boutique and salon"/><figcaption><span>03</span><div><b>Retail & salons</b><small>Checkout · customer convenience</small></div></figcaption></figure></div><div className="venueTypes"><span>RESTAURANTS</span><span>HOTELS</span><span>BARS</span><span>TRIBAL ENTERPRISES</span><span>SALONS</span><span>RETAIL</span><span>EVENT VENUES</span><span>MARKETS</span></div></section>

    <section className="section light" id="services"><Reveal><p className="eyebrow dark"><span/> The standard, reconsidered</p><div className="splitHead"><h2>An ATM should add to<br/>the room—not apologize<br/>for being in it.</h2><p>Most ATM companies compete on the machine. Sovereign Cash Co. competes on the entire experience: the placement, the service, the intelligence and the value created around it.</p></div></Reveal><div className="serviceGrid">{services.map(s=><article key={s.n}><span>{s.n}</span><h3>{s.title}</h3><p>{s.text}</p><ArrowRight/></article>)}</div></section>

    <section className="os" id="signalos"><div className="osIntro"><p className="eyebrow"><span/> The intelligence layer</p><h2>Meet Signal<span>OS</span>.</h2><p>Operational software that makes every placement smarter, every service call faster and every partnership clearer.</p><div className="featureList"><span><Gauge/> Predictive cash demand</span><span><Zap/> Live machine health</span><span><Route/> Smart service routing</span><span><CalendarDays/> Event surge planning</span><span><Languages/> Accessible, multilingual UX</span></div></div><div className="dashboard"><div className="dashTop"><div><Mark/><b>SignalOS</b></div><span>LIVE NETWORK <i/></span></div><div className="dashStats"><div><small>FLEET STATUS</small><strong>98.7%</strong><em>Operational</em></div><div><small>30-DAY VOLUME</small><strong>$428k</strong><em>↑ 12.4%</em></div><div><small>SERVICE PREVENTED</small><strong>17</strong><em>this month</em></div></div><div className="dashBody"><div className="chart"><small>WITHDRAWAL DEMAND · 7 DAYS</small><div className="bars">{[42,58,48,72,88,96,64].map((h,i)=><i key={i} style={{height:`${h}%`}}><span>{['M','T','W','T','F','S','S'][i]}</span></i>)}</div></div><div className="locations"><small>LOCATION HEALTH</small>{[['Tulalip Market','Optimal'],['Riverfront Hotel','Optimal'],['Harbor Hall','Service soon']].map((x,i)=><div key={x[0]}><span><i className={i===2?'warn':''}/>{x[0]}</span><em>{x[1]}</em></div>)}</div></div><p className="demoLabel">ILLUSTRATIVE PRODUCT CONCEPT · SAMPLE DATA</p></div></section>

    <section className="calculator light"><div><p className="eyebrow dark"><span/> Venue economics</p><h2>Make cash access<br/>work harder.</h2><p>Explore an illustrative monthly scenario. A real proposal would use your traffic, category and operating model.</p></div><div className="calcCard"><div className="controls"><label>Monthly transactions <output>{inputs.transactions}</output><input type="range" min="100" max="2000" step="50" value={inputs.transactions} onChange={e=>setInputs({...inputs,transactions:+e.target.value})}/></label><label>Guest surcharge <output>${inputs.surcharge.toFixed(2)}</output><input type="range" min="2" max="6" step=".25" value={inputs.surcharge} onChange={e=>setInputs({...inputs,surcharge:+e.target.value})}/></label><label>Illustrative venue share <output>{inputs.venueShare}%</output><input type="range" min="0" max="60" step="5" value={inputs.venueShare} onChange={e=>setInputs({...inputs,venueShare:+e.target.value})}/></label></div><div className="results"><small>PROJECTED MONTHLY</small><div><span>Gross surcharge volume</span><b>{money.format(calc.monthlySurcharge)}</b></div><div><span>Illustrative venue revenue</span><b>{money.format(calc.venueRevenue)}</b></div><div className="lift"><span>Potential on-site spend enabled*</span><b>{money.format(calc.estimatedSpendLift)}</b></div><p>*Conceptual estimate using ${inputs.lift} per withdrawal. Not a promise of performance.</p></div></div></section>

    <section className="experience" id="experience"><p className="eyebrow"><span/> Beyond the transaction</p><h2>Four ways to build a<br/><em>network with gravity.</em></h2><div className="innovationGrid">{innovations.map(([title,text,Icon],i)=>{const C=Icon as typeof Store;return <article key={title as string}><span>0{i+1}</span><C/><h3>{title as string}</h3><p>{text as string}</p></article>})}</div></section>

    <section className="hardware"><div className="hardwareVisual photo"><img src={`${import.meta.env.BASE_URL}images/placement-retail.webp`} alt="Obsidian and copper ATM complementing a luxury retail interior"/><span className="material m1">BRUSHED COPPER</span><span className="material m2">OBSIDIAN FINISH</span><span className="material m3">VENUE-MATCHED PLACEMENT</span></div><div><p className="eyebrow dark"><span/> Designed for the room</p><h2>Hardware as<br/>hospitality.</h2><p>Quietly premium, deliberately placed and finished to complement the venue. The machine becomes a trusted amenity—not visual clutter.</p><ul><li><Check/> Finish and placement matched to your interior</li><li><Check/> Complimentary visual mockup before installation</li><li><Check/> ADA-conscious placement and interaction</li><li><Check/> Cleanliness and presentation standards</li></ul><a className="darkLink" href="#partner">Show us your space <ArrowRight/></a></div></section>

    <section className="story" id="story"><div className="storyArt"><div className="storyRings"/><Mark/></div><div><p className="eyebrow"><span/> Ownership with intention</p><h2>Rooted here.<br/>Built to circulate<br/>value here.</h2><p>Sovereign Cash Co. is envisioned as a Native-owned company with a simple belief: infrastructure can be profitable and still strengthen the places it serves.</p><p>That means honest partnerships, opportunities for Native and local vendors, intentional cash access and technology that turns activity into a clearer story of community value.</p><blockquote>“Not a badge on the website.<br/>A standard for how we operate.”</blockquote><small>FOUNDING PRINCIPLE · CONCEPT LANGUAGE</small></div></section>

    <section className="process light"><p className="eyebrow dark"><span/> From placement to performance</p><h2>Simple for the venue.<br/>Obsessive behind the scenes.</h2><div>{[['01','Listen','We learn the space, guest patterns and what success means.'],['02','Design','We select the model, finish, placement and partnership structure.'],['03','Launch','Installation is coordinated around operations—not the other way around.'],['04','Optimize','SignalOS turns live performance into smarter service and clearer reporting.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

    <section className="quote"><CircleDollarSign/><p>“Your ATM shouldn’t be the ugliest thing in the room. It should feel like you chose it.”</p><small>SOVEREIGN CASH CO. · PLACEMENT STANDARD</small></section>

    <section className="faq light"><p className="eyebrow dark"><span/> The practical questions</p><div className="faqWrap"><h2>Clarity is part<br/>of the service.</h2><div>{faqs.map((f,i)=><article key={f[0]}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{f[0]}</span><ChevronDown/></button>{openFaq===i&&<p>{f[1]}</p>}</article>)}</div></div></section>

    <section className="partner" id="partner"><div className="partnerRings"/><p className="eyebrow"><span/> Complimentary placement concept</p><h2>Show us your space.<br/><em>We’ll show you the fit.</em></h2><p>Send us a photo of the area you have in mind. We’ll recommend the placement, finish and service model—and create a visual mockup for your business.</p><div className="partnerActions"><a className="button cream" href="mailto:hello@sovereigncash.co?subject=ATM%20placement%20review&body=Business%20name%3A%0ALocation%3A%0ABest%20contact%3A%0A%0AAttach%20a%20photo%20of%20the%20space%20you%20have%20in%20mind.">Request my free mockup <ArrowRight/></a><span>No commitment · Local consultation · Fully managed</span></div></section>
    <footer><a className="brand" href="#top"><Mark/><span>SOVEREIGN<br/><b>CASH CO.</b></span></a><div><span>Native-owned</span><span>Locally operated</span><span>Software-powered</span></div><p><b>Concept website.</b> Sovereign Cash Co. is a working brand and business concept. Visuals are illustrative placement concepts. Features, metrics, service areas, certifications and commercial terms require validation before public launch.</p><small>© 2026 SOVEREIGN CASH CO. CONCEPT · CASH ACCESS, BEAUTIFULLY PLACED.</small></footer>
  </main>
}
