import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Banknote, Calculator, CheckCircle2, CircleAlert, CreditCard, Landmark, LockKeyhole, Store, WalletCards } from 'lucide-react';

const usd = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const sources = [
  ['Bankrate · 2025 ATM Fee Study','Average operator surcharge: $3.22; average issuer out-of-network fee: $1.64; $4.86 combined.','https://www.bankrate.com/banking/checking/checking-account-survey/'],
  ['Federal Reserve · Regulation E §205.16','An operator must disclose the fee amount before commitment; a fee may be charged only after the customer elects to continue.','https://www.law.cornell.edu/cfr/text/12/205.16'],
  ['FDIC · Consumer Compliance Manual','Institutions may set their own ATM cash limits; the FDIC gives $250/day as a valid policy example.','https://www.fdic.gov/consumer-compliance-examination-manual/vi-1-expedited-funds-availability-act'],
  ['CFPB · Credit-card cash advances','Credit-card ATM withdrawals use a separate cash-advance limit and may add a fee plus immediate, usually higher, interest.','https://www.consumerfinance.gov/ask-cfpb/can-i-withdraw-money-from-my-credit-card-at-an-atm-en-34/'],
  ['FinCEN · Limited-service ATM guidance','A standard cash-dispensing ATM using the owner’s vault cash is generally not a money transmitter under the limited facts in the guidance.','https://www.fincen.gov/resources/statutes-regulations/guidance/application-definition-money-services-business-certain'],
  ['Green Check · Cannabis payment trends','Its 2024–2025 retail data says cash represented nearly 68% of average daily dispensary sales in 2024.','https://greencheckverified.com/cannabis-payment-trends-cash-to-digital/'],
  ['Herring Bank · ATM business guide','Cites 150–300 monthly transactions for an average independent placement and $2.50–$3.50 typical surcharges.','https://www.herringbank.com/learn/how-to-start-an-atm-business/'],
];

export function ResearchBrief(){
  useEffect(()=>{const oldTitle=document.title; document.title='ATM Economics · Confidential Brief'; const meta=document.createElement('meta'); meta.name='robots'; meta.content='noindex, nofollow, noarchive'; document.head.appendChild(meta); return()=>{document.title=oldTitle;meta.remove()}},[]);
  const [visits,setVisits]=useState(150); const [capture,setCapture]=useState(18); const [fee,setFee]=useState(4); const [withdrawal,setWithdrawal]=useState(100); const [cost,setCost]=useState(.35); const [fixed,setFixed]=useState(45);
  const m=useMemo(()=>{const tx=Math.round(visits*30*capture/100), gross=tx*fee, variable=tx*cost, net=gross-variable-fixed; return {tx,gross,variable,net,annual:net*12,cash:tx*withdrawal}},[visits,capture,fee,withdrawal,cost,fixed]);
  const scenarios=[['Conservative',75,12,3.5,270,945],['Working case',150,18,4,810,3240],['High-volume',300,22,4.5,1980,8910]];
  return <main className="brief">
    <header className="briefHeader"><a href={`${import.meta.env.BASE_URL}`}><ArrowLeft/> Sovereign Cash Co.</a><span><LockKeyhole/> Confidential working brief · direct-link access</span></header>
    <section className="briefHero"><div><p className="eyebrow"><span/> Research file 001 · August 2026</p><h1>The economics of an ATM<br/><em>inside a cannabis store.</em></h1><p>A decision brief on fee structure, card and withdrawal limits, operator economics, and the range of revenue a cash-intensive retail location could support.</p></div><aside><small>THE SHORT ANSWER</small><b>$3.22</b><span>2025 average ATM operator surcharge</span><hr/><p>A cannabis location could plausibly produce <strong>hundreds to low-thousands of withdrawals monthly</strong>—but store traffic and the share of customers who arrive without cash matter far more than the fee itself.</p></aside></section>
    <nav className="briefNav">{[['01','Fee anatomy'],['02','Limits & cards'],['03','Cannabis case'],['04','Revenue model'],['05','Risks'],['06','Sources']].map(x=><a href={`#brief-${x[0]}`} key={x[0]}><i>{x[0]}</i>{x[1]}</a>)}</nav>

    <section className="briefSection" id="brief-01"><div className="briefKicker"><span>01</span><p>Fee anatomy</p></div><div className="briefContent"><h2>One withdrawal can carry<br/>two separate ATM fees.</h2><div className="feeFlow"><article><Store/><small>FEE 1 · VISIBLE AT ATM</small><b>Operator surcharge</b><strong>$3.22 avg.</strong><p>Set by the ATM owner/operator. This is the primary revenue pool and must be disclosed before the user agrees.</p></article><span>+</span><article><Landmark/><small>FEE 2 · FROM CARD ISSUER</small><b>Out-of-network fee</b><strong>$1.64 avg.</strong><p>Set and retained by the customer’s bank. The ATM owner does not receive it; some accounts waive or reimburse it.</p></article><span>=</span><article className="dark"><WalletCards/><small>TYPICAL CUSTOMER COST</small><b>Combined fee</b><strong>$4.86 avg.</strong><p>Bankrate’s 2025 national result. A $4.00 cannabis-site surcharge could put the customer’s total near $5.64 if their issuer charges the average.</p></article></div><div className="callout"><CircleAlert/><p><b>Revenue is not the full surcharge by default.</b> The contract determines who keeps it. Processor charges, network economics, a host share, cash-loading service, telecom and equipment costs may come out before owner profit.</p></div></div></section>

    <section className="briefSection alt" id="brief-02"><div className="briefKicker"><span>02</span><p>Limits & cards</p></div><div className="briefContent"><h2>Who actually decides<br/>how much comes out?</h2><div className="limitStack"><article><i>1</i><div><b>The card issuer authorizes the transaction.</b><p>The customer’s bank or card issuer applies available balance, daily withdrawal allowance, fraud controls and card status. This is often the binding limit.</p></div></article><article><i>2</i><div><b>The ATM operator can impose a lower ceiling.</b><p>Per-transaction limits manage vault cash, denomination capacity and risk. A machine might allow $200 or $400 even when the bank permits more.</p></div></article><article><i>3</i><div><b>The stricter rule wins.</b><p>Requested cash must fit both limits and the available bills. Customers may attempt multiple withdrawals, but issuer daily limits and repeated surcharges still apply.</p></div></article></div><div className="cardGrid"><article><Banknote/><b>Debit / ATM card</b><p>Draws from deposit funds. Subject to issuer daily limits, operator limits and available balance. Standard use case.</p></article><article><CreditCard/><b>Credit card</b><p>Treated as a cash advance: separate lower limit, PIN requirement, potential ATM fee, issuer fee and interest usually beginning immediately.</p></article><article><WalletCards/><b>Prepaid card</b><p>Program-specific. ATM access can be allowed, restricted or unavailable; fees and limits come from the card agreement plus the ATM.</p></article></div><p className="fine"><b>There is no universal U.S. ATM withdrawal maximum.</b> Limits are contractual and operational—not a single nationwide number. Configure the machine around the expected cannabis basket and vault plan, then let the issuer approve or decline.</p></div></section>

    <section className="briefSection cannabis" id="brief-03"><div className="briefKicker"><span>03</span><p>Cannabis case</p></div><div className="briefContent"><h2>Why this venue can outperform<br/>ordinary retail.</h2><div className="statBand"><article><strong>68%</strong><p>Cash share of average daily cannabis retail sales in 2024, per Green Check’s 2024–2025 dataset.</p></article><article><strong>150–300</strong><p>Monthly withdrawals cited as an average independent ATM range—not cannabis-specific.</p></article><article><strong>3 levers</strong><p>Daily customer visits × ATM capture rate × accepted surcharge.</p></article></div><div className="thesis"><h3>The opportunity</h3><p>A dispensary has a built-in reason to access cash at the point of purchase. That can push usage above a generic retail placement, particularly when customers cannot use their preferred payment method and the nearest alternative ATM is inconvenient.</p><h3>The catch</h3><p>“68% cash sales” does <em>not</em> mean 68% will use the on-site ATM. Many arrive with cash. Others use compliant debit/ACH options, abandon the purchase, or choose a competing cash machine. The capture rate must be measured after installation.</p><h3>Do not confuse it with a cashless ATM</h3><p>This model assumes a real machine that dispenses currency. Point-of-banking or “cashless ATM” systems that disguise a retail purchase as an ATM withdrawal carry network-compliance risk and should not be treated as equivalent.</p></div></div></section>

    <section className="briefSection model" id="brief-04"><div className="briefKicker"><span>04</span><p>Revenue model</p></div><div className="briefContent"><p className="eyebrow dark"><span/> Adjustable underwriting model</p><h2>Build the store case<br/>from observable inputs.</h2><div className="modelGrid"><div className="modelControls">
      <label>Customer visits per day <output>{visits}</output><input type="range" min="25" max="500" step="5" value={visits} onChange={e=>setVisits(+e.target.value)}/></label>
      <label>On-site ATM capture <output>{capture}%</output><input type="range" min="3" max="40" value={capture} onChange={e=>setCapture(+e.target.value)}/></label>
      <label>Operator surcharge <output>${fee.toFixed(2)}</output><input type="range" min="2.5" max="7" step=".25" value={fee} onChange={e=>setFee(+e.target.value)}/></label>
      <label>Average withdrawal <output>${withdrawal}</output><input type="range" min="40" max="300" step="20" value={withdrawal} onChange={e=>setWithdrawal(+e.target.value)}/></label>
      <label>Variable cost per withdrawal <output>${cost.toFixed(2)}</output><input type="range" min="0" max="1.5" step=".05" value={cost} onChange={e=>setCost(+e.target.value)}/></label>
      <label>Fixed monthly operating cost <output>${fixed}</output><input type="range" min="0" max="500" step="5" value={fixed} onChange={e=>setFixed(+e.target.value)}/></label>
    </div><div className="modelResults"><Calculator/><small>ILLUSTRATIVE MONTHLY RESULT</small><div><span>Completed withdrawals</span><b>{m.tx.toLocaleString()}</b></div><div><span>Gross surcharge revenue</span><b>{usd.format(m.gross)}</b></div><div><span>Modeled variable + fixed costs</span><b>−{usd.format(m.variable+fixed)}</b></div><div className="heroResult"><span>Modeled net before tax & capital</span><b>{usd.format(m.net)}</b></div><div><span>Annualized modeled net</span><b>{usd.format(m.annual)}</b></div><div><span>Monthly vault cash dispensed</span><b>{usd.format(m.cash)}</b></div><p>Excludes equipment purchase/depreciation, financing, armored cash service, insurance, repairs, downtime, cash opportunity cost, revenue share and tax unless entered through the cost controls.</p></div></div>
      <div className="scenarioList"><div className="scenarioHead"><span>Scenario</span><span>Visits/day</span><span>Capture</span><span>Surcharge</span><span>Withdrawals/mo.</span><span>Gross/mo.</span></div>{scenarios.map(s=><div key={s[0] as string}>{s.map((v,i)=><span key={i}>{i===3?`$${Number(v).toFixed(2)}`:i===5?usd.format(Number(v)):i===2?`${v}%`:v}</span>)}</div>)}</div><p className="fine">These are sensitivity cases, not forecasts. At 150 visits/day, an 18% capture rate means 27 users/day or 810/month. Prove the capture assumption with store traffic, tender mix and actual ATM settlement reports.</p>
    </div></section>

    <section className="briefSection alt" id="brief-05"><div className="briefKicker"><span>05</span><p>Decision & risks</p></div><div className="briefContent"><h2>The deal structure matters<br/>as much as the location.</h2><div className="decisionGrid"><article><CheckCircle2/><b>Strongest economics</b><p>Own the machine and fund the vault cash, retain the surcharge, negotiate transparent processing, and measure uptime and capture daily.</p></article><article><CheckCircle2/><b>Lowest operational burden</b><p>Use a full-service placement and negotiate a fixed per-transaction host payment or defined surcharge split. Lower upside, less cash and service responsibility.</p></article><article><CircleAlert/><b>Biggest hidden drain</b><p>Cash loading. At 810 withdrawals × $100, the machine cycles $81,000 monthly. Loading frequency, idle vault cash and cash-out downtime can erase attractive spreadsheet margins.</p></article><article><CircleAlert/><b>Pricing risk</b><p>A higher surcharge raises revenue per completed withdrawal but may increase cancellations and customer irritation. Test $3.50–$4.50 before assuming $5+ is sustainable.</p></article></div><div className="nextResearch"><b>Next evidence to collect from a prospective store</b><span>Daily completed transactions by weekday</span><span>Average ticket and cash tender share</span><span>Current ATM withdrawal count, amount and surcharge</span><span>Existing operator contract and revenue share</span><span>Cash-out events, service calls and uptime</span><span>Nearest competing ATM and its displayed surcharge</span></div></div></section>

    <section className="briefSection sources" id="brief-06"><div className="briefKicker"><span>06</span><p>Source ledger</p></div><div className="briefContent"><h2>What this brief rests on.</h2><p>Research accessed August 27, 2026. Primary regulatory sources are used for legal mechanics; current industry sources provide market benchmarks. Commercial benchmarks should be validated against processor proposals and real placement data.</p><div>{sources.map((s,i)=><a href={s[2]} target="_blank" rel="noreferrer" key={s[0]}><i>{String(i+1).padStart(2,'0')}</i><span><b>{s[0]}</b><small>{s[1]}</small></span><ArrowUpRight/></a>)}</div><aside><LockKeyhole/><p><b>Access note.</b> This page is unlinked from the public site and marked for no indexing, but it is not authenticated. Anyone who receives the URL can open it. Add login protection before placing confidential partner or store data here.</p></aside></div></section>
    <footer className="briefFooter"><span>SOVEREIGN CASH CO. · INTERNAL RESEARCH</span><span>Living brief · Version 1.0</span></footer>
  </main>
}
